### ISSUE TITLE
홈화면에서 아래로 당겼을 때 흰색 배경 보이는 이슈

### ISSUE THREAD

**Issue by positiveko** [depromeet/ygtang-app#29]
## 할 일

- [ ]

**Comment by hyesungoh** [comment]
요거는 (아마도) #31 에서 해결됐을 수도 있어요!! 바운스 스크롤 옵션을 비활성화해서 ...!

근데 키보드가 올라왔다가 내려갈 때 같은 때에는 아주 살짝 보이는 거 같더라구요 !!

**Comment by positiveko** [comment]
저는 이제 보이지 않는 거 같은데 오늘 다들 테스트해보면 클로즈드 하는 걸로 해요~

**Comment by positiveko** [comment]
테스트플라이트 배포 후 홈화면 확인했습니다
