### ISSUE TITLE
웹뷰 내 gesture로 페이지 이동

### ISSUE THREAD

**Issue by positiveko** [depromeet/ygtang-app#42]
## 할 일

- [ ]

**Comment by positiveko** [comment]
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowsbackforwardnavigationgestures

이 프롭스로 해결할 수 있을지 확인 필요합니다!

**Comment by positiveko** [comment]
https://kdg-is.tistory.com/entry/React-Native-WebView-%EB%92%A4%EB%A1%9C%EA%B0%80%EA%B8%B0Android-ios

안드로이드 뒤로가기 활성화

**Comment by SenseCodeValue** [comment]
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#allowsbackforwardnavigationgestures

이걸로 IOS는 됩니다!
